services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - '*.log'
    depends_on:
      - redis
  redis:
    image: "redis:alpine"